### PR TITLE
[QOLDEV-640] update CKAN fork to turn logout into a POST

### PR DESCRIPTION
**Pull request by ThrawnCA**
- Logging out has side effects so it shouldn't be a GET. Changing to a POST will fix its interactions with caching and CSRF filtering.

### CODE REVIEW

**Review by duttonw — APPROVED** [review]

**Comment by duttonw** [comment]
bdd tests need fixing:
Substep info: Assertion Failed: FAILED SUB-STEP: Then I should see an element with xpath "//a[@title='Log out']"
      Substep info: Assertion Failed: Element with xpath "//a[@title='Log out']" not found

**Review by duttonw — CHANGES_REQUESTED** [review]
Substep info: Assertion Failed: FAILED SUB-STEP: Then I should see an element with xpath "//a[@title='Log out']"
 Substep info: Assertion Failed: Element with xpath "//a[@title='Log out']" not found

**Comment by ThrawnCA** [comment]
> Substep info: Assertion Failed: FAILED SUB-STEP: Then I should see an element with xpath "//a[@title='Log out']" Substep info: Assertion Failed: Element with xpath "//a[@title='Log out']" not found

Good, so we know our tests cover it :)

**Review by duttonw — APPROVED** [review]
of course, this will now need to be done on 'every' plugin we have bdd tests installed.

**Review by duttonw — APPROVED** [review]

**Pull request merged**
