### PR TITLE
QOLSVC-2187 fix redirect to force all unless on www

### PR DESCRIPTION
**Pull request by duttonw**

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Comment by ThrawnCA** [comment]
This needs a fix to how requirement files are handled, which is in https://github.com/qld-gov-au/ckan-qld-infrastructure/pull/355 (ckanext-qa now defaults to 2.10 requirements and has a special file for 2.9).

**Comment by duttonw** [comment]
@ThrawnCA  does develop pass?

**Comment by ThrawnCA** [comment]
> @ThrawnCA does develop pass?

Ah. Thanks to the removal of the test plugin code from the ckanext-data-qld repo, all the scenario tests relying on fixtures are failing.

I've updated all the relevant test config on https://github.com/qld-gov-au/ckan-qld-infrastructure/pull/355 and will see how it goes.

**Comment by duttonw** [comment]
not surprising staging now fails as fixed versions don't align with test changes
Tests Staging / OpenData STAGING py3 infrastructure build (pull_request) Failing after 29m

**Comment by duttonw** [comment]
@ThrawnCA  still no dice on opendata

Failing scenarios:
  test/features/resource_availability.feature:5  As a publisher, I can view hidden resources
  test/features/resource_availability.feature:18  As any user, I can see resources marked as visible and assessed
  test/features/search_facets.feature:4  When I go to the dataset list page, I can see the 'Data Portals' facet

16 features passed, 2 failed, 13 skipped
118 scenarios passed, 3 failed, 92 skipped
931 steps passed, 3 failed, 687 skipped, 0 undefined
Took 16m16.376s

**Pull request merged**
